version: '2'

services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        networks:
          crawler_network:
            ipv4_address: 172.25.0.50
        ports:
            - "5672:5673" # Expose ports to host (HOST:CONTAINER)
        expose:
            - "5673" # Expose ports without publishing them to the host machine

    database:
        hostname: mongo
        image: mongo:latest
        networks:
          crawler_network:
            ipv4_address: 172.25.0.70
        ports:
            - "27018:27017" # Expose ports to host (HOST:CONTAINER)
        expose:
            - "27017" # Expose ports without publishing them to the host machine

    worker:
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - .:/app
        links:
            - rabbit
        depends_on:
            - rabbit
        networks:
            - crawler_network

networks:
    crawler_network:
      driver: bridge
      ipam:
        config:
          - subnet: 172.25.0.0/24
